version: '3.8'

services:
  pix_mysql:
    image: mysql:8.0
    container_name: pix_mysql
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/infra/database/prisma/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql_data:
